" >>> SETUP >>>
syntax on
set autoindent
set smartindent
set number
set mouse=a
set showmatch
set smartcase
set autowrite
set wrap
set ttyfast
set laststatus=2
set showmode
set showcmd
set list
set listchars=tab:>\ ,trail:•,extends:#,nbsp:.
set hlsearch
set incsearch
" set rnu
set paste
set ruler
set tabstop=4
set shiftwidth=4
set expandtab


" >>> ALACRITTY >>>
set ttymouse=sgr


" >>> COLORSCHEME >>>
colorscheme monokai-bold


" >>> Plugins >>>
call plug#begin('~/.vim/plugged')
" >NERDtree
Plug 'scrooloose/nerdtree'

" >JEDI-vim
Plug 'davidhalter/jedi-vim'

" >SimplyFold
Plug 'tmhedberg/simpylfold'

" >PythonVenv
Plug 'jmcantrell/vim-virtualenv'

" >Vim-Polyglot
Plug 'sheerun/vim-polyglot'

" >YouCompleteMe
Plug 'valloric/youcompleteme', { 'do': './install.py --clang-completer --system-libclang' }

" >JS Syntax
Plug 'pangloss/vim-javascript'

" >Json
Plug 'elzr/vim-json'

" >Docker
Plug 'ekalinin/dockerfile.vim'

" >Cpp
Plug 'octol/vim-cpp-enhanced-highlight'

" >JSLib
Plug 'othree/javascript-libraries-syntax.vim'

" >Git
Plug 'tpope/vim-fugitive'

" >Markdown
Plug 'plasticboy/vim-markdown'

" >CrystalLinw
Plug 'rbong/vim-crystalline'

call plug#end()

" >>> NerdTree
nnoremap <C-n> :NERDtreeToggle

" >>>CrystalLine
function! StatusLine(...)
  return crystalline#mode() . crystalline#right_mode_sep('')
        \ . ' %f%h%w%m%r ' . crystalline#right_sep('', 'Fill') . '%='
        \ . crystalline#left_sep('', 'Fill') . ' %{&ft}[%{&fenc!=#""?&fenc:&enc}][%{&ff}] %l/%L %c%V %P '
endfunction
set statusline=%!StatusLine()
let g:crystalline_enable_sep = 'StatusLine'
let g:crystalline_statusline_fn = 'StatusLine'
let g:crystalline_theme = 'jellybeans'
set laststatus=2
