#!/bin/bash

case $DUNST_APP_NAME in
    NetworkManager)
        case $DUNST_SUMMARY in
            *Established*)
                ~/.config/shell-files/sound.sh net-connect
                ;;
            *Disconnected*)
                ~/.config/shell-files/sound.sh net-disconnect
                ;;
            *)
                exit
        esac
        ;;
    networkd)
        case $DUNST_BODY in
            *online*)
                ~/.config/shell-files/sound.sh net-connect
                    ;;
            offline)
                ~/.config/shell-files/sound.sh net-disconnect
                    ;;
            disconnected)
                ~/.config/shell-files/sound.sh net-disconnect
                ;;
            *)
                exit
        esac
        ;;
    *)
        case $DUNST_SUMMARY in
            WhatsApp)
                ~/.config/shell-files/sound.sh message
                ;;
            *)
                case $DUNST_BODY in
                    *)
                        ~/.config/shell-files/sound.sh notify
                        ;;
                esac
                ;;
        esac
        ;;
esac
